dogcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('dogs/', views.dogs_index, name='index'),
    path('dogs/<int:dog_id>/', views.dogs_detail, name='detail'),
    path('dogs/create/', views.DogCreate.as_view(), name='dogs_create'),
    path('dogs/<int:pk>/update/', views.DogUpdate.as_view(), name='dogs_update'),
    path('dogs/<int:pk>/delete/', views.DogDelete.as_view(), name='dogs_delete'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toy_detail'),
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('dogs/<int:dog_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('dogs/<int:dog_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    path('dogs/<int:dog_id>/unassoc_toy/<int:toy_id>/', views.unassoc_toy, name='unassoc_toy'),
    path('dogs/<int:dog_id>/add_photo/', views.add_photo, name='add_photo'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner'),
    ('S', 'Snack'),
    
)

# Create your models here.
class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def get_absolute_url(self):
        return reverse('toy_detail', kwargs={'pk': self.id })

    def __str__(self):
        return f"A {self.color} {self.name}"

class Dog(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'dog_id': self.id})

    def fed_for_today(self):
        return self.feeding_set.filter(date=date.today()).count() >= len(MEALS)


class Feeding(models.Model):
    date = models.DateField('Feeding Date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
  )

    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"

    class Meta:
         ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for dog_id: {self.dog_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic  import DetailView, ListView
from .models import Dog, Toy, Photo
from .forms import FeedingForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

import uuid
import boto3
import os

S3_BASE_URL = 'https://s3-us-east-2.amazonaws.com/'
BUCKET = 'dogcollector-sweetvanloan'

def some_function(request):
    my_key = os.environ['SECRET_KEY']

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def dogs_index(request):
    dogs = Dog.objects.filter(user=request.user)
    return render(request, 'dogs/index.html', { 'dogs': dogs })

@login_required
def dogs_detail(request, dog_id):
  dog = Dog.objects.get(id=dog_id)
  toys_dog_doesnt_have = Toy.objects.exclude(id__in = dog.toys.all().values_list('id'))
  feeding_form = FeedingForm()
  return render(request, 'dogs/detail.html', { 
      'dog': dog,
      'feeding_form': feeding_form,
      'toys': toys_dog_doesnt_have
      })

@login_required
def add_feeding(request, dog_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.dog_id = dog_id
        new_feeding.save()

    return redirect('detail', dog_id=dog_id)

@login_required
def assoc_toy(request, dog_id, toy_id):
    Dog.objects.get(id=dog_id).toys.add(toy_id)
    return redirect('detail', dog_id=dog_id)

@login_required
def unassoc_toy(request, dog_id, toy_id):
    Dog.objects.get(id=dog_id).toys.remove(toy_id)
    return redirect('detail', dog_id=dog_id)

@login_required
def add_photo(request, dog_id):
    photo_file = request.FILES.get('photo-file', None)

    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]

        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, dog_id=dog_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', dog_id=dog_id)

def signup(request):
    error_message = ''

    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'

    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)



class DogCreate(CreateView):
    model = Dog
    fields = ['name', 'breed', 'description', 'age']
    success_url = '/dogs/'

    def form_valid(self, form):
        form.instance.user = self.request.user 
        return super().form_valid(form)


class DogUpdate(UpdateView):
  model = Dog
  fields = ['breed', 'description', 'age']

class DogDelete(DeleteView):
  model = Dog
  success_url = '/dogs/'

class ToyCreate(LoginRequiredMixin, CreateView):
    model = Toy
    fields = '__all__'

class ToyDetail(LoginRequiredMixin, DetailView):
    model = Toy

class ToyList(LoginRequiredMixin, ListView):
    model = Toy

class ToyUpdate(LoginRequiredMixin, UpdateView):
    model = Toy
    fields = '__all__'

class ToyDelete(LoginRequiredMixin, DeleteView):
    model = Toy
    success_url = '/toys/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}



<h1>About the Dogcollector & Sweet Van Loan</h1>
<p>Dog Collector is an app for dog images and virtual pet interaction created by General Assembly Remote Immersive
    Software Engineering student Sweet Van Loan. Find more of her work on her <a
        href="https://github.com/sweetvanloan">Github</a>.</p>
<footer>All Rights Reserved, &copy; 2020 Cat Collector</footer>


{% endblock %}

main_app/templates/base.html
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dog Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper yellow darken-4">
                <ul>
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;DogCollector</a></li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about'%}">About</a></li>
                    <li><a href="/">Home</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'index' %}">View All My Dogs</a></li>
                    <li><a href="{% url 'dogs_create' %}">Add a Dog</a></li>
                    <li><a href="{% url 'toys_create' %}">Add A Toy</a></li>
                    <li><a href="{% url 'toys_index' %}">View All Toys</a></li>
                    <li><a href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer yellow darken-4">
        <div class="right">All Rights Reserved, &copy; 2020 Dog Collector &nbsp;</div>
    </footer>
</body>

</html>

main_app/templates/dogs/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Doggy's Dogged Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ dog.name }}</span>
                <p>Breed: {{ dog.breed }}</p>
                <p>Description: {{ dog.description }}</p>
                {% if dog.age > 0 %}
                <p>Age: {{ dog.age }}</p>
                {% else %}
                <p>Age: Puppy</p>
                {% endif %}
            </div>
            <div class="card-action">
                <a href="{% url 'dogs_update' dog.id %}">Edit</a>
                <a href="{% url 'dogs_delete' dog.id %}">Delete</a>
            </div>
        </div>
        {% for photo in dog.photo_set.all %}
        <img class="responsive-img card-panel" src="{{photo.url}}">
        {% empty %}
        <div class="card-panel teal-text center-align">No Photos Uploaded</div>
        {% endfor %}
        <form action="{% url 'add_photo' dog.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
            {% csrf_token %}
            <input type="file" name="photo-file">
            <br><br>
            <input type="submit" class="btn" value="Upload Photo">
        </form>
    </div>
    <div class="col s6">
        <form action="{% url 'add_feeding' dog.id %}" method="post">
            {% csrf_token %}
            {{ feeding_form.as_p }}
            <input type="submit" class="btn" value="Add Feeding">
        </form>
        <br>
        {% if dog.fed_for_today %}
        <div class="card-panel teal-text center-align">{{dog.name}} has been fed all meals for today</div>
        {% else %}
        <div class="card-panel red-text center-align">{{dog.name}} might be hungry</div>
        {% endif %}
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Meal</th>
                </tr>
            </thead>
            <tbody>
                {% for feeding in dog.feeding_set.all %}
                <tr>
                    <td>{{feeding.date}}</td>
                    <td>{{feeding.get_meal_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<hr>
<div class="row">
    <div class="col s6">
        <h3>{{ dog.name }}'s Toys</h3>
        {% if dog.toys.count %}
        {% for toy in dog.toys.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    A <span style="color: {{ toy.color.lower }};">{{ toy.color }}</span> {{ toy.name }}
                    <form action="{% url 'unassoc_toy' dog.id toy.id %}" method="post">
                        {% csrf_token %}
                        <button type=" submit" class="btn">Delete</button>
                    </form>
                </span>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>{{ dog.name }} has no toys!🐶</h5>
        {% endif %}
    </div>

    <div class="col s6">
        <h3>Available Toys</h3>
        {% if toys.count %}
        {% for toy in toys.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    A <span style="color: {{ toy.color.lower }};">{{ toy.color }}</span> {{ toy.name }}
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'assoc_toy' dog.id toy.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn">Add</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>{{dog.name}} Already Has All Toys Available!!</h5>
        {% endif %}
    </div>

    <script>
        var dateEl = document.getElementById('id_date');
        M.Datepicker.init(dateEl, {
            format: 'yyyy-mm-dd',
            defaultDate: new Date(),
            setDefaultDate: true,
            autoClose: true
        });

        var selectEl = document.getElementById('id_meal');
        M.FormSelect.init(selectEl);
    </script>

    {% endblock %}

main_app/templates/dogs/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Dog List</h1>

{% for dog in dogs %}
<div class="card">
    <a href="{% url 'detail' dog.id %}">
        <div class="card-content">
            <span class="card-title">{{ dog.name }}</span>
            <p>Breed: {{ dog.breed }}</p>
            <p>Description: {{ dog.description }}</p>
            {% if dog.age > 0 %}
            <p>Age: {{ dog.age }}</p>
            {% else %}
            <p>Age: puppy</p>
            {% endif %}
        </div>
    </a>
</div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Welcome to the DogCollector!</h1>

{% endblock %}

main_app/templates/main_app/dog_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Doggo</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' dog.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/dog_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Dog</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Toy</h1>

<h4>Are you sure you want to delete the <span class="{{object.color.lower}}-text"> {{ object.name }}</span>?</h4>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes-Delete!" class="btn">
    <a href="{% url 'toy_detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/toy_detail.html
{% extends 'base.html' %}

{% block content %}


<div class="card">
    <div class="card-content">
        <span class="card-title"><span class="{{object.color.lower}}-text">{{object.color}}</span>
            {{ object.name }}</span>
    </div>
    <div class="card-action">
        <a href="{% url 'toys_update' object.id %}">Edit</a>
        <a href="{% url 'toys_delete' object.id %}">Delete</a>
    </div>
</div>


{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Toy</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="btn" type="submit" value="Submit!">
</form>

{% endblock %}

main_app/templates/main_app/toy_list.html
{% extends 'base.html' %}

{% block content %}

{% for object in object_list %}
<div class="card">
    <a href="{% url 'toy_detail' object.id %}">
        <div class="card-content">
            <span class="card-title">A <span class="{{object.color.lower}}-text">{{object.color}}</span>
                {{ object.name }}</span>
        </div>
    </a>
</div>
{% endfor %}

{% endblock %}